### ISSUE TITLE
pprof doesn't respect the user's browser preference 

### ISSUE THREAD

**Issue by elichai** [google/pprof#581] opened 2020-11-18 10:23 UTC
Right now pprof open browsers first trying chrome variants, then firefox and then sensible-browser, and only at the end does it try `xdg-open`. https://github.com/google/pprof/blob/427632fa3b1c4f7ee2ec76e79aa1f7dc5bb25e28/internal/driver/commands.go#L346
This IMHO is this very invasive, as I have chromium installed for testing reasons but I do not want to open anything else in chromium, but `pprof` forces me to do that (altough I can set the `BROWSER` env variable).

Can we please make xdg-open the first priority? or at least query it for a default browser first (something like `xdg-mime query default x-scheme-handler/http`)

Thanks!

**Comment by nolanmar511** [comment] 2020-11-18 17:08
Duplicate of https://github.com/google/pprof/issues/389 (I believe)

**Comment by nolanmar511** [comment] 2020-11-19 22:53
Marking this as closed; I updated #389 a bit with what we'd tried and why it wasn't a good solution (`pprof -web` generates a SVG that's really best opened in a browser, so making  xdg-open the first priority results in some undesirable behavior).  We hadn't looked into querying the default browser.

Contributions are always appreciated!

**Closed by nolanmar511** 2020-11-19 22:53 UTC
