### ISSUE TITLE
pprof shows Unknown Java Frame in Graph format

### ISSUE THREAD

**Issue by sattishv** [google/pprof#453] opened 2019-02-06 11:43 UTC
Hi team,

pprof displays Unknown java frame in graph format. 

### What version of pprof are you using?
go version go1.11.5 linux/amd64

If you are using pprof via `go tool pprof`, what's your `go env` output?
If you run pprof from GitHub, what's the Git revision?
~$ go env    
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/cronusapp/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/cronusapp/Projects"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build097125834=/tmp/go-build -gno-record-gcc-switches"

### What operating system and processor architecture are you using?
Linux  4.4.0-133-generic #159~14.04.1-Ubuntu SMP Fri Aug 10 08:17:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### What did you do?
While viewing the profile in Graph view we could see few stacks with content unknown java frame.
Our app resides inside a docker container and we have installed go and pprof inside the container.
Eventhough we specified -XX:+PreserveFramePointer we could see the same behavior. 

Options used to attach java agent:
-agentpath:/opt/profiler_java_agent.so=-cprof_service=Sample,-cprof_profile_filename=%LOG_HOME%/profile_,-cprof_interval_sec=5,-cprof_duration_sec=800

We also don see the top functions its not working shows a blank page

### What did you expect to see?
All the stack frame with call graph details

### What did you see instead?

![screen shot 2019-02-06 at 5 04 42 pm](https://user-images.githubusercontent.com/7449241/52339193-6c95d180-2a32-11e9-9176-f4d72dcb205f.png)
Unknown Java Frame

**Comment by nolanmar511** [comment] 2019-02-06 17:38
@sattishv -- I'm marking this as closed, because I believe that the problem is with profile collection, not with pprof's visualization of the profile. But I have a few follow-up questions.

I'm assuming you're using aalexand's instructions for collecting profiles with the Stackdriver Profiler Java agent from [here](https://github.com/google/pprof/issues/346#issuecomment-378119331). Right?

What type of profile are you looking at? I would guess a thread profile, given that no units are specified, but I had thought the Java agent only supported Wall and CPU profile right now (I could be wrong on this, though)

+ @aalexand and @jqll for additional input.

**Comment by sattishv** [comment] 2019-02-06 17:56
Hi Team,

Thanks a lot Nolan. How abt top functions not been displayed. Do i need to open a separate ticket

Sattish.

**Comment by nolanmar511** [comment] 2019-02-06 18:28
You're using the `-http` output mode?

Do you seen anything printed in the terminal when you switch to the to top functions?
Does `pprof -top` or `pprof -list` generate output?
Can you reproduce with version of pprof available by downloading from github?

I wasn't able to reproduce with a different profile when using go1.11.5 on my machine (my output for go env does vary, though; particularly GOGCCFLAGS)



For reference, my output from `go env`:
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/usr/local/google/home/nolanmar/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/usr/local/google/home/nolanmar/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/google/home/nolanmar/.gimme/versions/go1.11.5.linux.amd64"
GOTMPDIR=""
GOTOOLDIR="/usr/local/google/home/nolanmar/.gimme/versions/go1.11.5.linux.amd64/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build059419685=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by aalexand** [comment] 2019-02-06 20:36
This should be filed and discussed in https://github.com/GoogleCloudPlatform/cloud-profiler-java.

**Closed by aalexand** 2019-02-06 20:36 UTC

**Comment by sattishv** [comment] 2019-02-07 11:54
Thanks for the response. Sure will file a ticket in cloud-profiler-java.
