### ISSUE TITLE
futex_wait_queue_me

### ISSUE THREAD

**Issue by HeinrichGit** [google/pprof#91] opened 2017-02-21 14:41 UTC
while running such a command
`go tool pprof -callgrind profile.log > profile.callgrind`
**pprof seems to be hanging**.

**System**: Go 1.8, Xenial 16.04, linux/amd64

**Comment by rauls5382** [comment] 2017-02-22 06:06
I can't reproduce this on my own system. Does it produce any output at all on profile.callgrind? Does it print any other error messages? Does it hang with this version of pprof, or only with the one from the go distribution?

**Comment by rauls5382** [comment] 2017-02-28 22:58
Closing as abandoned. Reopen if still an issue.

**Closed by rauls5382** 2017-02-28 22:58 UTC

**Comment by rsc** [comment] 2017-03-03 21:25
If you can reproduce this, please run

GOTRACEBACK=crash go tool pprof -callgrind profile.log >profile.callgrind 2>pprof.err

and then once you're convinced it is hung, type Ctrl-\ or send it a SIGABRT some other way. Then please attach pprof.err here. Thanks.
