### ISSUE TITLE
Source listing not found in webview while present in command line

### ISSUE THREAD

**Issue by Anon5710** [google/pprof#600] opened 2021-01-20 15:19 UTC
_**What version of pprof are you using?**_
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/USER/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/USER/go"
GOPROXY=""
GORACE=""
GOROOT="/home/USER/opt/go"
GOTMPDIR=""
GOTOOLDIR="/home/USER/opt/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build584220800=/tmp/go-build -gno-record-gcc-switches"

_**What operating system and processor architecture are you using?**_
Linux Ubuntu 18.04 x64

**_What did you do?_**
go tool pprof -http=":8000" -source_path=/home/USER/code/APP/src  APP cpuProfile.pprof
Open the source view, give it focus on "FUNCTION"

FUNCTION_PATH
bufio/bufio.go
  Total:           0      680ms (flat, cum)  3.39%
     48            .          .           ??? 
     49            .      680ms           ??? 
     55            .          .           ??? 
     56            .          .           ??? 
     75            .          .           ??? 
     78            .          .           ??? 
     79            .          .           ??? 
--> no source code visible

go tool pprof -source_path=/home/USER/code/APP/src  APP cpuProfile.pprof
(pprof) list FUNCTION
Total: 20.07s
ROUTINE ======================== FUNCTION_PATH in bufio/bufio.go
         0      680ms (flat, cum)  3.39% of Total
 Error: Could not find file bufio/bufio.go on path /home/USER/code/APP/src
ROUTINE ======================== FUNCTIONPATH in FUNCTION_GO_FILE_IN_GIVEN_PATH.go
--> starts listing source code here.

It seems that the webview doesn't show/find the source code, while the command line does.

**Comment by wyk9787** [comment] 2021-01-26 00:55
Thanks for filing the bug. Unfortunately I was not able to reproduce this issue with the profile and the benchmark program I have. Would you be able to share an example (code, binary & profile) that reproduces the issue?

**Comment by Anon5710** [comment] 2021-01-26 09:27
> Thanks for filing the bug. Unfortunately I was not able to reproduce this issue with the profile and the benchmark program I have. Would you be able to share an example (code, binary & profile) that reproduces the issue?

Unfortunately not as this is a product from my employer. As I am relatively new to golang, I'm unsure if I will be able to create an example.

**Comment by wyk9787** [comment] 2021-01-26 23:58
I see. It's hard to know what's going on without actually being able to reproduce the issue. I will leave this issue open so that if other people have encounter something similar, they can post it here and better yet to provide an example that reproduces the issue.

**Comment by nolanmar511** [comment] 2021-11-11 23:14
Looks like others haven't encountered this and we still can't reproduce, so closing.

**Closed by nolanmar511** 2021-11-11 23:14 UTC
